config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
   resources :articles do
    collection do
      get :update_article
      get :display
      get :published
     end
    end  
  get 'articles/show_article' 
  root 'articles#display'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_admin!
	def after_sign_out_path_for(resource)
		new_admin_session_path
	end	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
require 'httparty'#require 'rest-client'

def index
  url = "http://localhost:3001/articles"
  response = HTTParty.get(url)
  @data = JSON.parse(response.body)
 
end

def show
  url = "http://localhost:3001/articles/" + params[:id]
  @response = HTTParty.get(url)
end

def edit
 url = "http://localhost:3001/articles/" + params[:id]
 response = HTTParty.get(url)
 @data = JSON.parse(response.body)
 end

def update
  url = "http://localhost:3001/articles/"+ params[:id]
  options = { headers: { "Accept" => "application/json", "Content-Type" => "application/json" }, body: {"title" => params['title'], "description" => params['description'] , "date" => params['date'], "day" => params["day"] , "published" => params["published"]}.to_json }
  response = HTTParty.patch(url, options)
  @data =  JSON.parse(response.body)
  if response.code == 200
    if @data.update
    redirect_to articles_path
    flash[:notice] = 'API data updated successfully'
  else
    flash[:alert] = 'Error updating API data'
  end
 end 
end

def published
  url = "http://localhost:3001/articles/published_article"
  response = HTTParty.get(url)
  @data = JSON.parse(response.body)
  
end

def display
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/display.html.erb
<style>
  body {
    background-image: url('https://images.pexels.com/photos/262508/pexels-photo-262508.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');
    background-repeat: no-repeat;
    background-size: 100% 1300%;
  }
</style>

<div style="float: right;">
  <%= button_to'Logout', destroy_admin_session_path ,method: :delete %> 
</div> 

<div style="float: right;">
  <button type="button" ><%= link_to'Articles ',controller: 'articles' %></button>
</div>


<div class="align-self-center">
  <h1 style="color: darkblue;"><b>Welcome To Admin Application</b></h1>
</div>

app/views/articles/edit.html.erb
<style>
  body {    
   	background-color: lightsteelblue;
  }
</style>

<div class="d-flex align-items-center justify-content-center" style="height: 90vh">
	<div class="card" style="width: 20rem;" >
		<div class="card border-dark shadow-sm">
			<div class="card-body">
				<h2 class="card-title">Edit Article</h2>
<%= form_with url: article_path(@data["id"]), method: "put" do |form| %>
 	<div>
  	<%= form.label :title %><br>
		<%= form.text_field :title, value: @data["title"] %>
  </div>

  <div>
  	<%= form.label :Decription %><br>
		<%= form.text_field :description, value: @data["description"] %>

	<div>
  	<%= form.label :Date %><br>
		<%= form.text_field :date, value: @data["Date"] %>
  </div>

	<div>
  	<%= form.label :Day %><br>
		<%= form.text_field :day, value: @data["Day"] %>
  </div>

  <div>
  	<%= form.label :Published %><br>
		<%= form.text_field :published, value: @data["published"] %>
  </div><br>

	<div>
  		<%= form.submit %><br>
  	</div>
			<% end %>
	<div style="float: right;">
  	<button type="button" ><%= link_to'Back ',controller: 'articles' %></button>
	</div>
</div>
</div>
</div>
</div>

app/views/articles/index.html.erb
<center><h1 style="color:darkblue;"><b> Lists of Articles</b></h1></center>
<p>
  <%= flash[:notice] %>
</p>
<center>
   <table class="table align-middle">
  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Date</th>
      <th scope="col">Day</th>
    </tr>
  </thead>
  <tbody>
     <%  @data.each do |article| %>
    <tr>
      <td class="text-info"><%= article["title"] %></td> 
      <td><%= link_to 'show', article_path(article["id"]),class: "btn btn-outline-primary" %></td>
      <td><%= link_to 'update',edit_article_path(article["id"]),class: "btn btn-outline-info" %></td>
     </tr>
  <% end %>
</table></center>
 <button><%= link_to "Back", display_articles_path %></button>
<td><%= link_to 'Published Articles',published_articles_path,class: "btn btn-info" %></td>

 

app/views/articles/published.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col">Day</th>
    </tr>
   
   <%  @data.each do |article| %>
    <tr>
      <div class="badge bg-primary text-wrap" style="width: 6rem;">
      <td><%= article["title"] %></td> 
      <td><%= article["description"] %></td> 
      <td><%= article["date"] %></td>
      <td><%= article["day"] %></td>
    <% end %>
    </div>
  <tr>
  </table>
  <button type="button" ><%= link_to'Back ',controller: 'articles' %></button>

app/views/articles/show.html.erb
<h1 style="color: darkblue"><b> <%= @response['title'] %></b></h1><br>
<style >body {background-color: lightsalmon;}</style>


<p>
	<strong>Description :</strong>
   	<%= @response['description'] %>
</p>
<p>
	<strong>Date :</strong>
	<%= @response['date'] %>
</p>
<p>
	<strong>Day	:</strong>
	<%=@response['day'] %>
</p>
<p>
	<strong>Published</strong>
	<%=@response['published'] %>
</p>
  <button type="button" ><%= link_to'Back ',controller: 'articles' %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>